spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 2MB
  config:
    import: optional:file:.env[.properties]
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}  # S3 bucket region
      s3:
        region: ${AWS_REGION}
app:
  s3:
    bucket: ${S3_BUCKET}
okta:
  oauth2:
    issuer: ${auth-issuer}
    client-id: ${auth-client-id}
    client-secret: ${auth-client-secret}
